### ISSUE TITLE
vision.py: AttributeError: 'module' object has no attribute 'cv'

### ISSUE THREAD

**Issue by HoraceBury** [HackerHouseYT/AI-Smart-Mirror#58]
Got to the end of the instructions and everything works fine on macOS 10.12.6, then when running `python vision.py` I see this:

```
(hhsmartmirror) MyBook-Pro:AI-Smart-Mirror horace$ python vision.py
Traceback (most recent call last):
  File "vision.py", line 66, in <module>
    flags=cv2.cv.CV_HAAR_SCALE_IMAGE
AttributeError: 'module' object has no attribute 'cv'
```

I tried looking in the cv2.so file but it's a binary so I can't modify it. Any ideas?

**Comment by HoraceBury** [comment]
Found this post on SO:

[](https://github.com/rcrespocano/opencv-python/issues/2)

Just open the vision.py file and change lines 39 and 66 from this:

`flags=cv2.cv.CV_HAAR_SCALE_IMAGE`

To this:

`flags=cv2.CASCADE_SCALE_IMAGE`
